### ISSUE TITLE
Run.py 

### ISSUE THREAD

**Issue by emrekuruu** [aniltrue/OzU_GeniusWeb#1]
Run.py RESET_STORAGE causes an error. Method only takes 1 parameter .

**Comment by aniltrue** [comment]
In the orginal version, RESET_STORAGE feature does not exist. While clonning the newer version of the GeniusWeb from the orijinal repo to our repo, we forgot updating the corresponding method. 

Now, it is fixed. You can use RESET_STORAGE as described in README document.
