### ISSUE TITLE
Package Issues

### ISSUE THREAD

**Issue by A-D-Alamdari** [aniltrue/OzU_GeniusWeb#3]
The **_lightgbm_** package installation fails. I got the message below:
note: This is an issue with the package mentioned above, not pip.

**Comment by aniltrue** [comment]
Did you check your Python version (it should be 3.9) and requirements' versions?

**Comment by girra-emir** [comment]
I also had the same problem. You need to explicitly install the wheel package first. so pip3 install wheel, solved that problem for me. @aniltrue maybe we can add the wheel package to the requirements?

**Comment by aniltrue** [comment]
Requirements files are updated.
